theme: minima
title: Welcome to William's Blog
author: William Anil
email: wanil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
Enjoy my first post.
show_excerpts: true # set to false to remove excerpts on the homepage
