theme: minima
title: Will's Blog
author: William Anil 
description: > # this means to ignore newlines until "baseurl:"
  Here I will talk about certain aspects of my life.

Usernames:

Snapchat: b4obama
Instagram: w_i_l_l_0_3_3

show_excerpts: true # set to false to remove excerpts on the homepage

