theme: minima
title: Welcome to William's Blog
author: William Anil
email: wanil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
#Here, I will talk about certain aspects of my life. I hope you enjoy!
show_excerpts: true # set to false to remove excerpts on the homepage
